# -*- mode: ruby -*-
# vi: set ft=ruby :

# Check Vagrant dependencies
if !Vagrant.has_plugin?("vagrant-vbguest")
      system('vagrant plugin install vagrant-vbguest')

     raise("vagrant-vbguest installed. Run command \"vagrant up\" again.");
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.require_version '>= 1.8.0'
Vagrant.configure(2) do |config|

  # Create and configure the Server VM
  config.vm.define :mailproxylinux do |srv|
    srv.vm.box = "ubuntu/trusty64"
    # Assign additional private network
    srv.vm.network "private_network", ip: "172.16.0.10"
    srv.vm.hostname = "mailproxylinux"
    srv.vm.synced_folder "../fabric", "/fabric", create: true
    srv.vm.synced_folder "../conf", "/conf", create: true
    srv.vm.synced_folder "../data", "/data", create: true
    # Configure CPU & RAM per settings
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    # Provisioner BashShell
    srv.vm.provision "shell", path: "./script_server.sh"
  end

  # Create and configure the Client VM
  config.vm.define :clientlinux do |cli|
    cli.vm.box = "ubuntu/trusty64"
    # Assign additional private network
    cli.vm.network "private_network", ip: "172.16.0.50"
    cli.vm.hostname = "clientlinux"
    cli.vm.synced_folder "../fabric", "/fabric", create: true
    cli.vm.synced_folder "../conf", "/conf", create: true
    cli.vm.synced_folder "../data", "/data", create: true
    # Configure CPU & RAM per settings
    cli.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    # Provisioner BashShell
    cli.vm.provision "shell", path: "./script_client.sh"
  end
end


#Some extra commands that where tested for sync folders:
#srv.vm.synced_folder "../sample-lamp-compose", "/lamp_grey_demo", create: true, mount_options: ["dmode=777", "fmode=666"]
#srv.vm.synced_folder "../sample-lamp-compose", "/lamp_grey_demo", :mount_options => ["uid=0,gid=0"]
